# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 847088d825dd62edc0ab285544155703f774a1c3c9a0dd921a6b7f49ef1382bb4b67149058216a6ce43fb268e1c3f598a0c8768bf56c5fb6804d33d6cfd5605b

test:
  secret_key_base: 1f84ed91e86aded9df580fe1a69fa8888e60f17c17d92682c164b89f8558f859274e086ce90d4036bf2a47da258d7846fdef31969f80eda45f02d01dac0467b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
